// @ts-check
// Note: type annotations allow type checking and IDEs autocompletion

const lightCodeTheme = require("prism-react-renderer/themes/github");
const darkCodeTheme = require("prism-react-renderer/themes/dracula");

/** @type {import('@docusaurus/types').Config} */
const config = {
  title: "ShopBuilder App",
  tagline: "",
  url: "https://docs.shopbuilder.app",
  baseUrl: "/",
  onBrokenLinks: "warn",
  onBrokenMarkdownLinks: "warn",
  favicon: "img/favicon.ico",

  organizationName: "shopbuilder-app", // Usually your GitHub org/user name.
  projectName: "shopbuilder-app.github.io", // Usually your repo name.
  deploymentBranch: "gh-pages",
  // Docusaurus recommends "trailingSlash:false", but that gives me an error on build.
  //[ERROR] Error: ENOENT: no such file or directory, open 'C:\dev\docu-notion\build\.html'
  trailingSlash: true,

  presets: [
    [
      "classic",
      /** @type {import('@docusaurus/preset-classic').Options} */
      ({
        docs: {
          routeBasePath: "/", // Serve the docs at the site's root
          sidebarPath: require.resolve('./sidebars.js'), //  `undefined` to create a fully autogenerated 
        }, 
        blog: false,
        theme: {
          customCss: [
            require.resolve("./src/css/custom.css"),
            require.resolve(
              "./src/css/gifplayer.css"
              //"./node_modules/react-gif-player/dist/gifplayer.css" // this gave a big red compile warning which is seaming unrelated "  Replace Autoprefixer browsers option to Browserslist config..."
            ),
          ],
        },
      }),
    ],
  ],
  i18n: {
    defaultLocale: "en",
    locales: ["en", "fr"],
    localeConfigs: {
      en: {
        label: "English",
        direction: "ltr",
        htmlLang: "en-US",
        calendar: "gregory",
      },
    },
  },
  themes: [
    // ... Your other themes.
    [
      require.resolve("@easyops-cn/docusaurus-search-local"),
      {
        // ... Your options.
        // `hashed` is recommended as long-term-cache of index file is possible.
        hashed: true,
        // language: ["en", "fr"],
        indexBlog: false,
        indexPages: false,
        docsRouteBasePath: "/",
      },
    ],
  ],
  themeConfig:
    /** @type {import('@docusaurus/preset-classic').ThemeConfig} */
    ({
      metadata: [
        {
          name: "keywords",
          content: "ShopBuilder App - Flutter App Builder",
        },
      ],
      sitemap: {
        // https://www.sitemaps.org/protocol.html#xmlTagDefinitions
        changefreq: "weekly",
        priority: 0.5,
        ignorePatterns: [],
      },
      navbar: {
        title: "",
        logo: {
          alt: "Logo",
          src: "img/logo.png",
          srcDark: 'img/logo_dark.png',
          href: 'https://shopbuilder.app',
          target: '_self',
        },

        items: [
          {
            href: 'https://docs.shopbuilder.app',
            position: 'left',
            className: 'header-link',
            label: 'Docs',
          },
          {
            href: 'https://shopbuilder.app/pricing/',
            position: 'left',
            className: 'header-link',
            label: 'Pricing',
          },
         
        ],
      },

      prism: {
        theme: lightCodeTheme,
        darkTheme: darkCodeTheme,
      },
    }),
};

module.exports = config;
