/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    'Introduction',
    {type: 'doc',id: 'download-and-install'},
    {type: 'doc',id: 'sign-up-and-login'},
   
//     {
//       type: 'category',
//       label: 'Design',
//       items: [
//         {
//           type: 'autogenerated', 
//           dirName: 'Design',
//         },
//       ]
//     },
//     {
//       type: 'category',
//       label: 'Features',
//       items: [
//         {
//           type: 'autogenerated', 
//           dirName: 'Features',
//         },
//       ]
//     },
//     {
//       type: 'category',
//       label: 'Build Apps',
//       items: [
//         {
//           type: 'autogenerated', 
//           dirName: 'Build Apps',
//         },
//       ]
//     },
//     {
//       type: 'category',
//       label: 'Other',
//       items: [
//         {
//           type: 'autogenerated', 
//           dirName: 'Other',
//         },
//       ]
//     },
//     {
//       type: 'category',
//       label: 'Changelog',
//       items: [
//         {
//           type: 'autogenerated', 
//           dirName: 'Changelog',
//         },
//       ]
//     },
  ],

  // But you can create a sidebar manually
  
  // tutorialSidebar: [
  //   {
  //     type: 'category',
  //     label: 'Tutorial',
  //     items: ['hello'],
  //   },
  // ],
   
};

module.exports = sidebars;
